# Generated by Django 2.2.9 on 2020-09-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.TextField(null=True, verbose_name=False),
        ),
    ]
